package punto_venta_java;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/*
 * @author El Paketaxo azul
 */
public class Punto_Venta_Java extends javax.swing.JFrame {

    String[][] arreglo = {{"1", "Burro percheron", "100"},
    {"2", "Hot dogs de la uni", "60"},
    {"3", "Ensalada", "130"},
    {"4", "Enchiladas", "80"},
    {"5", "Torta de civil", "100"}};

    double total = 0;
    String cantidad_pattern = "((?<id>([0-9]+)))\\*(?<cantidad>([0-9]+))";
    String cantidad_uno = "((?<id>([0-9]+)))";

    public Punto_Venta_Java() {
        initComponents();
        setLayout(null);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = ((int) tk.getScreenSize().getWidth());
        int ySize = ((int) tk.getScreenSize().getHeight());
        setSize(xSize, ySize);
        getContentPane().setBackground(new Color(25, 47, 110));
        table.setBounds(0, 0, xSize, ySize);

        JTableHeader th = table.getTableHeader();
        TableColumnModel tcm = th.getColumnModel();
        TableColumn tc1 = tcm.getColumn(0);
        TableColumn tc2 = tcm.getColumn(1);
        TableColumn tc3 = tcm.getColumn(2);
        TableColumn tc4 = tcm.getColumn(3);
        tc1.setHeaderValue("Precio");
        tc2.setHeaderValue("Nombre");
        tc3.setHeaderValue("Cantidad");
        tc4.setHeaderValue("Total");
        th.repaint();
        introducirDatos.setText("\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        introducirDatos = new javax.swing.JTextPane();
        totallabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 102));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        introducirDatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        introducirDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                introducirDatosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(introducirDatos);

        totallabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totallabel.setForeground(new java.awt.Color(255, 255, 255));
        totallabel.setText("Total = ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed


    }//GEN-LAST:event_tableKeyPressed

    private void introducirDatosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_introducirDatosKeyPressed

        //introducirDatos.setText("");
        if (evt.VK_ENTER == evt.getKeyCode()) {
            String texto = introducirDatos.getText();
            String remove = texto.substring(1, texto.length());
            introducirDatos.setText("");
            Pattern p = Pattern.compile(cantidad_pattern);
            Matcher m = p.matcher(remove);
            Pattern p2 = Pattern.compile(cantidad_uno);
            Matcher m2 = p2.matcher(remove);
            int indexOf = remove.indexOf("*");
            try {
                String id = remove.substring(0, indexOf);
                String cantidad = remove.substring(indexOf + 1, remove.length());
                for (int i = 0; i < arreglo.length; i++) {
                    if (m.matches()) {
                        if (id.equals(arreglo[i][0])) {
                            DefaultTableModel modelo = (DefaultTableModel) table.getModel();
                            Object[] fila = new Object[6];
                            fila[0] = arreglo[i][2];
                            fila[1] = arreglo[i][1];
                            fila[2] = cantidad;
                            fila[3] = Float.parseFloat(arreglo[i][2]) * Float.parseFloat(cantidad);
                            modelo.addRow(fila);
                            table.setModel(modelo);
                            total += Double.parseDouble(arreglo[i][2]) * Double.parseDouble(cantidad);
                            totallabel.setText("Total = " + total);
                        }
                    }
                }
            } catch (Exception e) {

            }

            if (m2.matches()) {
                for (int i = 0; i < arreglo.length; i++) {
                    if (remove.equals(arreglo[i][0])) {
                        DefaultTableModel modelo = (DefaultTableModel) table.getModel();
                        Object[] fila = new Object[6];
                        fila[0] = arreglo[i][2];
                        fila[1] = arreglo[i][1];
                        fila[2] = 1 + "";
                        fila[3] = Float.parseFloat(arreglo[i][2]);
                        modelo.addRow(fila);
                        table.setModel(modelo);
                        total += Double.parseDouble(arreglo[i][2]);
                        totallabel.setText("Total = " + total);
                    }
                }
            }

        } else if (evt.VK_ESCAPE == evt.getKeyCode()) {
            try {
                
                DefaultTableModel modelo = (DefaultTableModel) table.getModel();
                String temp =table.getValueAt(table.getRowCount()-1, 3).toString();
                total -= Double.parseDouble(temp);
                totallabel.setText("Total = " + total);
                modelo.removeRow(table.getRowCount() - 1);
                table.setModel(modelo);
            } catch (Exception e) {

            }
        }


    }//GEN-LAST:event_introducirDatosKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Punto_Venta_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Punto_Venta_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Punto_Venta_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Punto_Venta_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Punto_Venta_Java().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane introducirDatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JLabel totallabel;
    // End of variables declaration//GEN-END:variables

}
